services:
  server:
    build:
      context: ./server
    restart: always
    env_file:
      - ./server/.env 
    ports:
      - '5000:5000' 
    depends_on:
      - db
    networks:
      - app-network

  # React Frontend Service
  client:
    build:
      context: ./client
    restart: always
    environment:
      REACT_APP_API_URL: http://server:5000
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'Inventorydb'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    expose:
      - '3306'
    networks:
      - app-network

volumes:
  my-db:

networks:
  app-network:
    driver: bridge
